# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification'),
        ),
    ]
