# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160919_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[(1, 'Publier'), (0, 'Dépublier')], max_length=5),
        ),
    ]
