# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20160928_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='height_field',
            field=models.IntegerField(default=700, verbose_name="Hoteur de l'image"),
        ),
        migrations.AlterField(
            model_name='article',
            name='width_field',
            field=models.IntegerField(default=1024, verbose_name="Largeur de l'image"),
        ),
    ]
