# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160928_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='menu',
            field=models.BooleanField(default=False),
        ),
    ]
