# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_section_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='menu',
            new_name='is_SectionMenu',
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_CategorieMenu',
            field=models.BooleanField(default=True),
        ),
    ]
