# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160930_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='is_CategorieMenu',
            field=models.BooleanField(default=False),
        ),
    ]
