# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20160930_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMagasine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('fileMagazine', models.FileField(upload_to='magazines')),
                ('image', models.ImageField(upload_to='', verbose_name='Couverture')),
            ],
        ),
    ]
