# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_uploadmagasine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmagasine',
            name='fileMagazine',
            field=models.FileField(upload_to='magazines', verbose_name='Document'),
        ),
    ]
